- platform: darksky
  api_key: !secret forecast_key
  monitored_conditions:
    - summary
#    - precip_type
#    - precip_intensity
#    - precip_intensity_max
    - temperature
    - temperature_max
    - temperature_min
#    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - nearest_storm_distance
    - minutely_summary
#    - pressure
    - visibility
#    - ozone
  update_interval:
    # At least one of these must be specified:
    days: 0
    hours: 0
    minutes: 1
    seconds: 30
    milliseconds: 0

- platform: nest
  monitored_conditions:
#     - 'temperature'
#     - 'target'
      - 'humidity'
#     - 'operation_mode'
#     - 'last_connection'
#     - 'co_status'
#     - 'smoke_status'

- platform: moon
