#-------------------------------------------
#  PiHole ad Blocking Related Packages
#-------------------------------------------
homeassistant:
  customize:

    sensor.pihole_ads_percentage_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.pihole_domains_being_blocked:
      friendly_name: Total Domains Blocking
      icon: mdi:do-not-disturb

    sensor.pihole_ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon: mdi:do-not-disturb

    sensor.pihole_dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text

    sensor.radecicpihole:
      friendly_name: Pi Hole Server
      icon: mdi:filter-variant

    group.pihole:
      homebridge_hidden: true
#-------------------------------------------
sensor:
  - platform: pi_hole
    host: 10.0.1.37
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today

  - platform: template
    sensors:
      radecicpihole:
        friendly_name: 'Radecic-PiHole'
        value_template: "{{ 'Online' if is_state('device_tracker.radecicpihole', 'home') else 'Offline' }}"
